// src/constants/error-codes.ts

/**
 * Standard error codes used across the application
 */
export const ErrorCodes = {
  // Authentication errors
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',

  // Configuration errors
  CONFIG_ERROR: 'CONFIG_ERROR',
  CONFIG_MISSING_ENV: 'CONFIG_MISSING_ENV',
  CONFIG_INVALID_VALUE: 'CONFIG_INVALID_VALUE',

  // Key Vault errors
  KEYVAULT_ERROR: 'KEYVAULT_ERROR',
  KEYVAULT_SECRET_NOT_FOUND: 'KEYVAULT_SECRET_NOT_FOUND',
  KEYVAULT_ACCESS_DENIED: 'KEYVAULT_ACCESS_DENIED',

  // Salesforce errors
  SALESFORCE_ERROR: 'SALESFORCE_ERROR',
  SALESFORCE_AUTH_FAILED: 'SALESFORCE_AUTH_FAILED',
  SALESFORCE_API_ERROR: 'SALESFORCE_API_ERROR',
  SALESFORCE_RATE_LIMIT: 'SALESFORCE_RATE_LIMIT',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_MISSING_FIELD: 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',

  // Generic errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
